name: Automatically create release branches
on:
  schedule:
    # This is where we schedule when to create a new release branch, but
    # the cron syntax doesn’t allow for “every 3 weeks” so we’ll run our
    # action every week and then check in the action (python script)
    # whether it’s time for a release yet.
    #
    # cron format is: minute hour day-of-month year day-of-week.  A ’*’
    # means all possible values, day-of-week starts with 0 for Sunday.
    # GitHub times are UTC. Thus the following is: Midnight UTC at the
    # start of Friday
    - cron: '0 0 * * 5'

jobs:
  scheduled_release_branch_maker_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3'
      - name: install dependencies
        run: pip install PyGithub semver
      - name: run our branch maker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        # The python script that does the work takes a single optional
        # argument which is the minimum number of days between releases.
        # Thus if we want to make a release every 3 weeks, we schedule
        # the time and day of the week above and specify 20 (days) here.
        # If no argument is given the script creates a release branch
        # unconditionally.
        run: python make-release-branch.py 20
